# Generated by Django 5.0.1 on 2024-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0002_alter_sensor_tipo_contadordata_luminosidadedata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umidadedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
